# Stage I
FROM node:22-alpine3.20 AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage II copy to nginx

FROM nginx:latest

ARG NGINXCONF

COPY ${NGINXCONF} /etc/nginx/conf.d

COPY --from=builder /usr/src/app/dist/ /usr/share/nginx/html

EXPOSE 80
# EXPOSE 443
