version: "3.8"

services:
  portfolio-client-production:
    image: portfolio-client-production:${ENV}
    restart: unless-stopped
    ports:
      - "7080:80"
      - "7443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - portfolio-production

  portfolio-server-production:
    image: portfolio-server-production:${ENV}
    restart: unless-stopped
    env_file:
      - ./server/${ENV}.env
    ports:
      - "7001:7001"
    networks:
      - portfolio-production

networks:
  portfolio-production:
    driver: bridge
