version: "3.8"

services:
  portfolio-client-production:
    image: portfolio-client-production:${ENV}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    #voulmes:
    networks:
      - portfolio-production

  production-server-production:
    image: portfolio-server-production:${ENV}
    restart: unless-stopped
    env_file:
      - ./server/${ENV}.env
    ports:
      - 7001:7001
    networks:
      - portfolio-production

networks:
  portfolio-production:
    driver: bridge
